[package]
name = "ITV"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
image = "0.24.5"
term_size = "0.3.2"
termsize = "0.1.6"
